ACIM_Answeres =
[
	[(localize "STR_CW_ACIM_ANSWER_GETOUTOFEYES"), 4],
	[(localize "STR_CW_ACIM_ANSWER_PLAYHERO"), 4],
	[(localize "STR_CW_ACIM_ANSWER_HOWAREYOU"), 4],
	[(localize "STR_CW_ACIM_ANSWER_SORRYNOLANG"), 4],
	[(localize "STR_CW_ACIM_ANSWER_PREGNANT"), 4],
	[(localize "STR_CW_ACIM_ANSWER_YOUNOTFROMHERE"), 4],
	[(localize "STR_CW_ACIM_ANSWER_YOKE"), 4],
	[(localize "STR_CW_ACIM_ANSWER_MYPEOPLENEEDME"), 4],
	[(localize "STR_CW_ACIM_ANSWER_NOTHINGTOSAY"), 8],
	[(localize "STR_CW_ACIM_ANSWER_FUCKOFF"), 4],
	[(localize "STR_CW_ACIM_ANSWER_ONHOLIDAY"), 4],
	[(localize "STR_CW_ACIM_ANSWER_ILIKEYOURSHOES"), 4],
	[(localize "STR_CW_ACIM_ANSWER_TIME"), 4],
	[(localize "STR_CW_ACIM_ANSWER_DIGUP"), 4],
	[(localize "STR_CW_ACIM_ANSWER_GOHOME"), 4],
	[(localize "STR_CW_ACIM_ANSWER_WHATSUP"), 4]
];
