ACIM_Funds_Backpack = [
	
	[(localize "STR_CW_ACIM_FINDS_Nothing"),9],	
	[(localize "STR_CW_ACIM_FINDS_Morphine"),3],		
	[(localize "STR_CW_ACIM_FINDS_Cloth"),7],				
	[(localize "STR_CW_ACIM_FINDS_Duct Tape"),6],			
	[(localize "STR_CW_ACIM_FINDS_Toolbox"),6],			
	[(localize "STR_CW_ACIM_FINDS_Scrap Metal"),4],		 
	[(localize "STR_CW_ACIM_FINDS_Note"),6],			
	[(localize "STR_CW_ACIM_FINDS_Mortar Shell"),2], 		
	[(localize "STR_CW_ACIM_FINDS_Money"),7],			
	[(localize "STR_CW_ACIM_FINDS_Knife"),3],		
	[(localize "STR_CW_ACIM_FINDS_Water Bottle"),7],		
	[(localize "STR_CW_ACIM_FINDS_Canned Food"),7],
	[(localize "STR_CW_ACIM_FINDS_C4 Explosive"),1],			
	[(localize "STR_CW_ACIM_FINDS_Cookbook"),6],		
	[(localize "STR_CW_ACIM_FINDS_Baseball"),6],			
	[(localize "STR_CW_ACIM_FINDS_Battery"),8],			
	[(localize "STR_CW_ACIM_FINDS_Bible"),8],			
	[(localize "STR_CW_ACIM_FINDS_Book"),5],				
	[(localize "STR_CW_ACIM_FINDS_Car Battery"),3],			
	[(localize "STR_CW_ACIM_FINDS_Potato Chips"),5],		 
	[(localize "STR_CW_ACIM_FINDS_Box of Cigars"),5],		 
	[(localize "STR_CW_ACIM_FINDS_Cigarettes"),8],			
	[(localize "STR_CW_ACIM_FINDS_Clipboard"),4],			
	[(localize "STR_CW_ACIM_FINDS_Cooked Meat"),5],		 
	[(localize "STR_CW_ACIM_FINDS_Dogtag"),7],				
	[(localize "STR_CW_ACIM_FINDS_Folded Map"),8],		
	[(localize "STR_CW_ACIM_FINDS_Hard Drive"),3],			 
	[(localize "STR_CW_ACIM_FINDS_Harmonica"),4],			
	[(localize "STR_CW_ACIM_FINDS_Lighter"),5],				
	[(localize "STR_CW_ACIM_FINDS_Penicillin"),3],			
	[(localize "STR_CW_ACIM_FINDS_Raw Meat"),7],			
	[(localize "STR_CW_ACIM_FINDS_Rock"),7],				
	[(localize "STR_CW_ACIM_FINDS_SD Card"),4],				
	[(localize "STR_CW_ACIM_FINDS_Soda Can"),6],			 
	[(localize "STR_CW_ACIM_FINDS_Teddy Bear"),3],		 
	[(localize "STR_CW_ACIM_FINDS_Tin Can"),5],				
	[(localize "STR_CW_ACIM_FINDS_USB Drive"),4],			
	[(localize "STR_CW_ACIM_FINDS_Wallet"),7],				
	[(localize "STR_CW_ACIM_FINDS_Whiskey"),5],				
	[(localize "STR_CW_ACIM_FINDS_Can of Paint"),4],		  
	[(localize "STR_CW_ACIM_FINDS_Candy Bar"),8],		
	[(localize "STR_CW_ACIM_FINDS_Beer"),6], 			
	[(localize "STR_CW_ACIM_FINDS_Boltcutter"),3],
	[(localize "STR_CW_ACIM_FINDS_Carrot"),7],	
	[(localize "STR_CW_ACIM_FINDS_Cereal"),8],				
	[(localize "STR_CW_ACIM_FINDS_Coffee"),5],				
	[(localize "STR_CW_ACIM_FINDS_Corn"),6],				
	[(localize "STR_CW_ACIM_FINDS_Dino Toy"),5],			
	[(localize "STR_CW_ACIM_FINDS_Dirty Water"),6],		
	[(localize "STR_CW_ACIM_FINDS_Energy Drink"),4],		
	[(localize "STR_CW_ACIM_FINDS_Gum"),8],					
	[(localize "STR_CW_ACIM_FINDS_Hammer"),6],			
	[(localize "STR_CW_ACIM_FINDS_Keycard"),4],				
	[(localize "STR_CW_ACIM_FINDS_Moonshine"),3],		
	[(localize "STR_CW_ACIM_FINDS_Nails"),7],				
	[(localize "STR_CW_ACIM_FINDS_Potato"),8],				
	[(localize "STR_CW_ACIM_FINDS_Razor"),3],				
	[(localize "STR_CW_ACIM_FINDS_Sandbag"),6], 				
	[(localize "STR_CW_ACIM_FINDS_Sugar"),5],		
	[(localize "STR_CW_ACIM_FINDS_Wrench"),5],				
	[(localize "STR_CW_ACIM_FINDS_Donut"),5],			
	[(localize "STR_CW_ACIM_FINDS_Empty Bottle"),8],	
	[(localize "STR_CW_ACIM_FINDS_Gas Mask"),2],
	[(localize "STR_CW_ACIM_FINDS_Laptop"),5],				
	[(localize "STR_CW_ACIM_FINDS_Rope"),8],				
	[(localize "STR_CW_ACIM_FINDS_Snoballs"),4],				
	[(localize "STR_CW_ACIM_FINDS_Tablet"),3],			
	[(localize "STR_CW_ACIM_FINDS_Twinkies"),6]	
	
];