ACIM_Funds_Vest = [
	[(localize "STR_CW_ACIM_FINDS_Nothing"),9],	
	[(localize "STR_CW_ACIM_FINDS_Morphine"),3],		
	[(localize "STR_CW_ACIM_FINDS_Cloth"),6],				
	[(localize "STR_CW_ACIM_FINDS_Duct Tape"),6],			
	[(localize "STR_CW_ACIM_FINDS_Note"),4],			
	[(localize "STR_CW_ACIM_FINDS_Money"),6],			
	[(localize "STR_CW_ACIM_FINDS_Knife"),3],		
	[(localize "STR_CW_ACIM_FINDS_C4 Explosive"),2],			
	[(localize "STR_CW_ACIM_FINDS_Baseball"),5],			
	[(localize "STR_CW_ACIM_FINDS_Battery"),7],			
	[(localize "STR_CW_ACIM_FINDS_Potato Chips"),6],		 
	[(localize "STR_CW_ACIM_FINDS_Cigarettes"),6],			
	[(localize "STR_CW_ACIM_FINDS_Dogtag"),6],				
	[(localize "STR_CW_ACIM_FINDS_Folded Map"),6],		
	[(localize "STR_CW_ACIM_FINDS_Harmonica"),5],			
	[(localize "STR_CW_ACIM_FINDS_Lighter"),8],				
	[(localize "STR_CW_ACIM_FINDS_Penicillin"),3],			
	[(localize "STR_CW_ACIM_FINDS_Rock"),7],				
	[(localize "STR_CW_ACIM_FINDS_SD Card"),7],				
	[(localize "STR_CW_ACIM_FINDS_USB Drive"),5],			
	[(localize "STR_CW_ACIM_FINDS_Wallet"),8],				
 	[(localize "STR_CW_ACIM_FINDS_Candy Bar"),8],		
	[(localize "STR_CW_ACIM_FINDS_Carrot"),8],		
	[(localize "STR_CW_ACIM_FINDS_Gum"),8],					
	[(localize "STR_CW_ACIM_FINDS_Keycard"),6],				
	[(localize "STR_CW_ACIM_FINDS_Nails"),7],				
	[(localize "STR_CW_ACIM_FINDS_Potato"),7],				
	[(localize "STR_CW_ACIM_FINDS_Razor"),3],				
	[(localize "STR_CW_ACIM_FINDS_Donut"),7],			
	[(localize "STR_CW_ACIM_FINDS_Rope"),6],				
	[(localize "STR_CW_ACIM_FINDS_Snoballs"),6],				
	[(localize "STR_CW_ACIM_FINDS_Tablet"),4],			
	[(localize "STR_CW_ACIM_FINDS_Twinkies"),7]	
];