
//NOTHING SPECIAL HERE!!! CLOSE IT!!!!

acim_fnc_updateUsedItemsArray = {
ACIM_INVENTORY_TEMP_USEDITEMNAMES = ACIM_INVENTORY_TEMP_USEDITEMNAMES_SHIRT + ACIM_INVENTORY_TEMP_USEDITEMNAMES_SHOES + ACIM_INVENTORY_TEMP_USEDITEMNAMES_PANTS + ACIM_INVENTORY_TEMP_USEDITEMNAMES_VEST + ACIM_INVENTORY_TEMP_USEDITEMNAMES_BACKPACK;
};